### PR TITLE
Good work.

### PR DESCRIPTION
**Pull request by aMarCruz**
:+1:

### CODE REVIEW

**Comment by aMarCruz** [comment]
just for fun
alternative for 'Parse selector' in h()
```javascript
var selector = "div#foo.bar.boo";  //test
var props = {};  //test

var re  = /[#\.]([^#\.]+)/g;

//para mostrar las ocurrencias que se encontrarán
var cls = '';
selector = selector.replace(re, function(ch, token) {
  ch = ch[0];
  if (ch === '#') {
    props.id = token;
  } else if (ch === '.') {
    cls ? (cls += ' ' + token) : (cls = token);
  }
  return '';
});
props.className = cls;

//test...
console.log(selector);
console.log(props.id);
console.log(props.className);
//output:
//div
//foo
//bar boo
```

**Comment by paldepind** [comment]
Hello

Thanks a lot for your corrections :) Great catches!

I don't know how you found this library. But since you're here let me share my goals:

1/ Clean and simple virtual DOM implementation – mostly done.
2/ Performance – (I have implemented the vdom benchmark and it looks good).
3/ Advanced hooks for implementing components – not done.

**Comment by paldepind** [comment]
Your selector parser is really clever! And it handles when the id is not first. Like `div.some#id.class`. But it's a bit longer.

**Comment by aMarCruz** [comment]
thanks @paldepind 
yeah, the selector parser is verbose and I don't test it, but I think is fast. Benchmark it, there is only one call to replace and only work if neccesary.
Good luck.

**Pull request merged**
