### PR TITLE
Pr dataset module

### PR DESCRIPTION
**Pull request by hville**
new dataset module and module tests as discussed in #90

### CODE REVIEW

**Comment by paldepind** [comment]
Thank you @hville. This is a great extra convenience to have :smile:

**Comment by krainboltgreene** [comment]
No documentation was added to the README.md for this :(

**Comment by hville** [comment]
@paldepind I don't mind adding documentation but I was concerned it would crowd-up the main page since it more of a niche module. If you want, I could create a separate `readme.md` in the modules folder to park info for current and future modules.

@krainboltgreene With the `dataset` module installed, you can do `h('div', {dataset: {foo: 'foo'}})`. This has the same result as`h('div', {attrs: {'data-foo': 'foo'}})` with the `attributes` module.

**Comment by krainboltgreene** [comment]
Oh shit, that's awesome.

We should do that for all the microformats like aria and itemprop.

**Pull request merged**
