### PR TITLE
Failed spec when using mixed keyed & non-keyed virtual nodes.

### PR DESCRIPTION
**Pull request by jails**
Nice implementation !
However just wanted to warn you that your patching algorithm doesn't work well when playing with keyed & non-keyed virtual nodes, there's probably still a minor glitch somewhere.

### CODE REVIEW

**Comment by paldepind** [comment]
Thank you :)

Thanks for letting me know. I'll take a look at it. How did you discover this?

**Comment by jails** [comment]
I found your `updateChildren()` algorithm so sexy that I wanted to adapt it for a personnal virtual dom projet. Since I wasn't able to make a spec to pass I added the spec in your test suite to see where I was wrong, but it didn't pass either :-p

**Comment by paldepind** [comment]
I'm glad you find it sexy! Feel free to borrow whatever you want :) The children reconciliation is somewhat inspired by the one used in cito.js and kivi (they use almost the exact same algorithm).

It's really great that you found this issue! It's definitely a lot nice to discover while writing tests than in actual usage. The commit cd7eb76a should fix the issue.

**Comment by jails** [comment]
Awesome it works great now :+1: !
No prob, I will keep you updated if I found other ordering issues ;-)

**Pull request merged**
